name: "testing Git Hub Actions!"

on:
  push:
    branches: ["main"]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - run: echo "1st job executed"

  second-job:
    # Conditional: if main is the reference, then run the jon, context.
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job # First job must run first (secuential)
    runs-on: ubuntu-latest

    steps:
      - name: Second job
        run: echo "second job executed"
      - name: Printing secret  
        run: echo "${{ secrets.SECRET_TOKEN }}"

  installing services:
    runs-on: ubuntu-latest
    steps:
    - name: Install redis cli
      run: sudo apt-get update -y && sudo apt-get install redis-tools -y

    - name: Test redis
      run: redis-cli -h localhost -p 6379 ping